artifact_uri: file:///c:/Users/marks/OneDrive/Desktop/TSYP_AESS/runs/mlflow/580114391019369842/a0d71b0acda246e29bc4810b289dbdd6/artifacts
end_time: null
entry_point_name: ''
experiment_id: '580114391019369842'
lifecycle_stage: active
run_id: a0d71b0acda246e29bc4810b289dbdd6
run_name: train6
run_uuid: a0d71b0acda246e29bc4810b289dbdd6
source_name: ''
source_type: 4
source_version: ''
start_time: 1733067046682
status: 1
tags: []
user_id: marks
