artifact_location: file:///c:/Users/marks/OneDrive/Desktop/TSYP_AESS/runs/mlflow/0
creation_time: 1733067045456
experiment_id: '0'
last_update_time: 1733067045456
lifecycle_stage: active
name: Default
